apiVersion: v1
kind: Service
metadata:
  name: mybackendlb-clusterid

spac:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      
  selector: 
    component: backend
    app: my-app